- name: print used memory
  hosts: localhost
  tasks:
    - name: get memory
      ansible.builtin.shell: free | grep Mem
      register: free

    - name: print free variable
      ansible.builtin.debug:
        msg: "{{ free.stdout }}"

#since the output of the above is giving the extra data which is not needed so we will write code to get only stdout data
